[package]
name = "parallel_programming"
version = "0.1.0"
authors = ["Ryohei Suzuki <ryh.szk.cmnty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.27"
